version: "3.8"
services:
  app:
    image: khv9786/als_ide_jdk
    ports:
      - "8090:8080"
    depends_on:
      - db
    networks:
      - backend
    container_name: ${COMPILER_CONTAINER_NAME:-compiler}
    volumes:
      - ./data:/app


  db:
    image: mysql:latest
    platform: linux/x86_64
    restart: always
    ports:
      - "3308:3306" # 중첩방지로 3308
    environment:
      MYSQL_ROOT_PASSWORD: "!db1234" # Root pw
      MYSQL_PASSWORD: "!als1234" # 생성되는 DB pw
      MYSQL_DATABASE: als_ide_db # DB 이름
      MYSQL_USER: user # 사용자 이름
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d

    healthcheck: # 컨테이너 상태 체크용
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge